version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Pass123
    ports:
      - "1433:1433"
  
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: ecommerce-dbeaver
    ports:
      - "8978:8978"
    depends_on:
      - sqlserver